### ISSUE TITLE
stack CDN random error (core-worker-container)

### ISSUE THREAD

**Issue by dbourasseau** [dngroup/t-nova#1]
some time we get 

```
     ID: core-worker-container
    Function: docker.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1624, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/dockerio.py", line 331, in mod_watch
                  installed_status = installed(name=name, **kw)
                File "/usr/lib/python2.7/dist-packages/salt/states/dockerio.py", line 707, in installed
                  out = create(image_name, **kw)
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerio.py", line 714, in create_container
                  raise e
              TypeError: create_host_config() got an unexpected keyword argument 'mem_limit'
     Started: 18:26:19.429930
    Duration: 18.401 ms
     Changes:   
```

**Comment by nherbaut** [comment]
what is the default version of docker.io installed on the system?
try to install the latest version of docker.io

2016-02-29 18:28 GMT+01:00 dbourasseau notifications@github.com:
